### Recuperar todas las peliculas
GET http://localhost:1234/movies

### Recuperar pelicula por ID
GET http://localhost:1234/movies/dcddefad-a94c-4810-8acc-5f188d3b18c3

### Recuperar todas las peliculas por  genero
GET http://localhost:1234/movies?genre=terror

### crear una pelicula
POST http://localhost:1234/movies
Content-Type: application/json

{
	"title": "Matrix",
	"year": 1999,
	"director": "Lana",
	"duration": 142,
	"poster": "https://i.ebayimg.com/images/g/4goAAOSwMyBe7hnQ/s-11200.webp",
	"genre": [
		"Terror",
		"Crime"
	],
	"rate": 9.3
}

### crear una pelicula
POST http://localhost:1234/movies
Content-Type: application/json

{
	"title": "Matrix",
	"year": "mm"
}

### Actualizar una película

PATCH  http://localhost:1234/movies/dcddefad-a94c-4810-8acc-5f188d3b18c3
Content-Type: application/json

{
	"year": 2020
}

### Eliminar una peliculas
DELETE http://localhost:1234/movies/dcddefad-a94c-4810-8acc-5f188d3b18c3